{ config, pkgs, lib, user, homeDir, ... }:

let
  isLinux = pkgs.stdenv.isLinux;
  isWorkUser = user == "mtr21pqh";
in {
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    matchBlocks = {
      "*" = {
        sendEnv = [ "LANG" "LC_*" ];
        hashKnownHosts = true;
        addKeysToAgent = "yes";
        extraOptions = {
          ControlMaster = "auto";
          ControlPath = "~/.ssh/sockets/%r@%h-%p.%C";
          ControlPersist = "600";
        };
      };
      "github.com" = {
        identitiesOnly = true;
        identityFile = [
          (if isLinux then "/home/${user}/.ssh/id_mgrbyte_github" else "/Users/${user}/.ssh/id_mgrbyte_github")
        ];
      };
    };
  };

  # Redirect HM-generated SSH config to a staging path so ~/.ssh/config
  # is free for activation-time composition with the decrypted work config.
  # Fabric/Paramiko don't support Include directives, so we inline instead.
  home.file.".ssh/config".target = ".ssh/config_base";

  # Compose ~/.ssh/config by concatenating the decrypted work config
  # with the base config generated by home-manager.
  home.activation.composeSshConfig =
    lib.hm.dag.entryAfter [ "linkGeneration" "createSecretSymlinks" ] ''
      _base="${homeDir}/.ssh/config_base"
      _target="${homeDir}/.ssh/config"
      _work="${homeDir}/.secrets/ssh-config-work"

      if [[ -f "$_base" ]] || [[ -L "$_base" ]]; then
        rm -f "$_target"
        {
          ${lib.optionalString isWorkUser ''
          if [[ -f "$_work" ]]; then
            cat "$_work"
            printf '\n'
          else
            echo "# WARNING: work SSH config not yet decrypted" >&2
          fi
          ''}
          cat "$_base"
        } > "$_target"
        chmod 0600 "$_target"
      fi
    '';

  home.activation.ensureSshSocketsDir = lib.hm.dag.entryAfter ["writeBoundary"] ''
    mkdir -p ${homeDir}/.ssh/sockets
  '';
}
